generate:
  - client
accessModifier: public
additionalImports:
  - MistralAPITypes
# filter:
#   tags:
#     - Assistants
#     - Audio
#     - Audit Logs
#     - Batch
#     - Chat
#     - Completions
#     - Embeddings
#     - Evals
#     - Files
#     - Fine-tuning
#     - Images
#     - Models
#     - Moderations
#     - Uploads